### ISSUE TITLE
escape costs 5256c when directly inputted but 5536c in definition

### ISSUE THREAD

**Issue by 837951602** [fasttime/JScrewIt#10]
Change the def of 'D' to escape and see its being directly connect the six letters while d-input generates `15610201..toString(32)+'e'`

**Comment by fasttime** [comment]
I can't seem to reproduce this in 2.6. `D` uses the same optimized code as `escape`, plus a little more. How exactly are you getting 5536 chars?

**Comment by 837951602** [comment]
Do you get a whole 'D' in 5908c?

**Comment by fasttime** [comment]
Hm, I'm getting a whole 'D' in 5625 chars. Maybe you should git pull the repo again and switch to branch 2.6.

**Comment by 837951602** [comment]
Solved
