### ISSUE TITLE
FEATURES

### ISSUE THREAD

**Issue by 837951602** [fasttime/JScrewIt#16]
Why are ['NODECONSTRUCTOR','IE_SRC'] not compatible?

**Comment by fasttime** [comment]
Probably not necessary. Investigating now.

**Comment by 837951602** [comment]
Let them compatible or make NODECONSTRUCTOR lead to NO_IE_SRC

**Comment by 837951602** [comment]
JScrewIt.Feature.areCompatible(['IE11','IE10']) is false, but IE10 for "Internet Explorer 10 or later" and IE11 for  "Internet Explorer 11" so Internet Explorer 11 is included by both

**Comment by fasttime** [comment]
`IE10` and `IE11` are not compatible because `DOCUMENT` (`IE10`) and `HTMLDOCUMENT` (`IE11`) exclude each other. So the description is inaccurate.

**Comment by fasttime** [comment]
Fixed in https://github.com/fasttime/JScrewIt/commit/bd3b6786a08b5257db0e92abe98a7c128ee4561b and https://github.com/fasttime/JScrewIt/commit/cacde451b8e4df39c709cf6a5954f4e7db79528c.

**Comment by 837951602** [comment]
Why doesn't IE10 refer to IE9(and the same types) but repeat the list again?

**Comment by 837951602** [comment]
https://github.com/fasttime/JScrewIt/issues/6#issuecomment-279214422
If defined NO_IE_SRC, NO_V8_SRC, NO_FF_SRC, is it now easy to check it as not compatible when three are all chosen?

**Comment by fasttime** [comment]
Keeping a list of individual features is easier to maintain. What for example if a new feature is invented that only fits IE 9 but not IE 10?

When `NO_FF_SRC` is introduced, `V8_SRC` will be redefined as a union of `NO_FF_SRC` and `NO_IE_SRC`. Same thing for `IE_SRC` and `FF_SRC`. Taking the union of all three `NO_` features will not be allowed, at least until a new JS engine with its own format for native functions comes up (I hope not!).

**Comment by 837951602** [comment]
(V8/IE/FF)_SRC will be defined into neither the other two, and All the [NO_IE_SRC, NO_V8_SRC] change into FF_SRC
We don't hope a new native function style appear either, even if in normal proggraming. Some environment may use it as a testing for whether it's a native function or not.

**Comment by 837951602** [comment]
Does https://github.com/fasttime/JScrewIt/compare/master...837951602:patch-4 NO_**_SRC unioning mean?

**Comment by fasttime** [comment]
Done
