### ISSUE TITLE
Optimize some single char

### ISSUE THREAD

**Issue by 837951602** [fasttime/JScrewIt#17]
for IE9
'\\' 5120
`([].filter.constructor('return/false/')().constructor('\n')+[])[1]` 2438
`([].filter.constructor('return/false/')().constructor([].filter)+[])[1]` 2428
For some environment(e.g.Chrome*) it returns '\n', but for IE9 it's '\\'

**Comment by 837951602** [comment]
besides, RegExp([].filter) just can pass(no syntax error), but I don't know what can pass it

**Comment by 837951602** [comment]
Cuz the recent two optimizations(this and https://github.com/fasttime/JScrewIt/issues/3#issuecomment-287815206) need new features, it'd be necessary to test the known environments out.
Guess this is for IE 9+(IE8 doesn't support, but since IE8 have no [].filter, it's blocked from JSFUCK), and status for browsers

**Comment by 837951602** [comment]
Are RegExp('\n')+''=='/\\\n/' and RegExp('/')=='/\\/' the same feature?

**Comment by fasttime** [comment]
They are different. `RegExp('/') == '/\\//'` could be true in all engines (haven't tested) in which case it doesn't need a feature.

**Comment by 837951602** [comment]
I tested on IE, Maxthon, Chrome.
RegExp('\n')+''=='/\\n/' RegExp('/')=='/\//'
IE T T
Chrome F T
MaxThon F F

**Comment by fasttime** [comment]
Ok. BTW IE 8 and Maxthon are not supported at this time: https://github.com/fasttime/JScrewIt#compatibility

**Comment by 837951602** [comment]
I know. but since we are talking about some features that not found, we try to make all that support [].filter can use

**Comment by 837951602** [comment]
And CharEncodeByEval may meet near beater: [IE9]
[].filter.constructor('return"'+
  ([].filter.constructor('return/false/')()
  .constructor('false'.italics())+[])[10]+
'u003B"')() 5749
';' 5135
[].filter.constructor('return"'+
  ([].filter.constructor('return/false/')()
  .constructor('false'.italics())+[])[10]+
'u0021"')() 5012
'!' 5095

**Comment by 837951602** [comment]
```
encode('"&"','ESC_HTML_ALL').length
2508
encode('"".fontcolor("".italics())[13]','ESC_HTML_ALL').length
1700

**Comment by fasttime** [comment]
It seems that `RegExp('/') == '/\\//'` does not happen in older versions of Node.js. I was planning to deprecate Node.js < 4 in a next major release, but until then we need a new feature.

**Comment by 837951602** [comment]
```
encode('"".fontcolor("&")','ESC_HTML_ALL').length = 3750
ncode('"".fontcolor("".fontcolor("".italics()))','ESC_HTML_ALL').length = 2918
Wnough space to find the &amP; amd win

**Comment by fasttime** [comment]
Thanks! I'm still working on this.

**Comment by fasttime** [comment]
I've also updated ";" and "q". Unfortunately, it's not possible to get "p" in that way because the `&` in `"".fontcolor("&")` is not escaped as `&amp;`, not even in Android Browser engines (the only ones where `ESC_HTML_ALL ` is available).

**Comment by 837951602** [comment]
```
encode('"D"','ANY_DOCUMENT').length = 4490
encode('(document+[]).slice("-10")[1]','ANY_DOCUMENT').length = 4489

**Comment by fasttime** [comment]
Looks good. We have to change [this definition](https://github.com/fasttime/JScrewIt/blob/67d2872bc480b1f6768b817924ccb3a064284a99/src/lib/definitions.js#L801).

**Comment by fasttime** [comment]
I think the character definitions are all set up now. I'm still unhappy because I can't generate the output.txt any more like before and check for conflicts/circular references/unused definitions/etc. This is something I need to get fixed before I can move on to implement new features.

**Comment by 837951602** [comment]
Does it cost too much time or just throw errors?

**Comment by fasttime** [comment]
It takes forever because it scans all possible feature branches for every single character. There must be a way to get this done faster, at least I hope so.

**Comment by 837951602** [comment]
I'm now running the gulp with `scanning character definitions [============        ] 59% 3245.4s`. I'll check it 12h later

**Comment by 837951602** [comment]
Is the scanning slow because the output is really too large so even if you can directly get the whole table you can't write, or just because the way is bad?

**Comment by fasttime** [comment]
The algorithm is bad. It's because the scanner tries to encode every character with and without every feature it finds on its way, even for features that are just queried but don't make any difference. I've started to work on this already but I haven't had much time lately.

**Comment by fasttime** [comment]
This is all implemented in the update branch now.
