### ISSUE TITLE
supplementary plane optimazation

### ISSUE THREAD

**Issue by Clayblockunova** [fasttime/JScrewIt#25]
currently, supplementary plane characters like emojis are escaped into 2 surrogate characters. But current JS have alternate methods to treat supplementary plane characters as single character,  i.e. String.fromCodePoint(),  decodeURI() (like unescape() but treat standard UTF8 better) and \u{XXXXXX}(alternate Escape sequence). when will those be supported?

**Comment by fasttime** [comment]
That's a good point. I was planning to work on number encoding (#9) first, since that alone would improve the length of many character encodings even in the BMP character range, but I haven't been very active here lately. The optimization you describe is probably simpler and can be done first.

**Comment by fasttime** [comment]
This is now implemented in JScrewIt 2.28.
