### ISSUE TITLE
Minor platform support

### ISSUE THREAD

**Issue by Clayblockunova** [fasttime/JScrewIt#27]
Currently,  the tool only have major browser (i.e. IE, Firefox, Chromium-based browsers, Safari and Android browser) and Node.JS support.  Should we add support for minor and local browser (e.g. Konqueror, UC, Yandex) and non-browser JS engine (e.g. Nashorn, lv, IronJS) now?

**Comment by fasttime** [comment]
I'm afraid that maintaining specific features for less common environments would be too much work for me to afford.

That said, JScrewIt probably already runs in new versions of minor browsers and non-browser engines, even if those are not tested.

To encode whatever you want in an unsupported browser (e.g. Yandex), open JScrewIt in that browser, then in the compatibility dropdown select "Only this browser".

In other non-browser engines like Rhino, you can run for example:

```js
JScrewIt.encode('"Hello, World!"', { features: 'AUTO' });
```

This will generate an encoding that is specific for that particular engine (`AUTO` is the equivalent of "Only this browser").

If you spot a problem with JScrewIt in some exotic engine, even in an supported one, feel free to open an issue here and we'll see what we can do.

**Comment by Clayblockunova** [comment]
and, will you add support of game consoles(Nintendo Switch, Wii&WiiU, NDS&3DS, PS3,4&5, Xbox 360, One & Series X)?

**Comment by fasttime** [comment]
JScrewIt supports the major browsers on any platform, including game consoles (e.g. Edge for Xbox). Note that some features may be different, though. For example, Chrome on iOS uses a different engine than the desktop browser, and so it needs a different encoding.

**Comment by Clayblockunova** [comment]
afaik, Sony devices like PS3,4&5 and newer Nintendo devices like Switch and 3DS uses NetFront (developed in Japan) as default browser, and idk how its JS works.

**Comment by Clayblockunova** [comment]
sorry for bothering you again. will you add support of NetFront(which PS3,4&5, Nintendo Switch and 3DS browser are based on)?
