### ISSUE TITLE
How to encode escape characters such as '\\' and '\"'

### ISSUE THREAD

**Issue by Umbrahin** [fasttime/JScrewIt#32]
I tried to get the encoding of `"`, but all failed

<img width="262" alt="Screen Shot 2021-08-02 at 11 33 30 AM" src="https://user-images.githubusercontent.com/71512917/127801021-adfc77aa-a6d5-484f-8b60-0198fb18f8ac.png">

I pasted the output into the console and got the following error

<img width="237" alt="Screen Shot 2021-08-02 at 11 36 13 AM" src="https://user-images.githubusercontent.com/71512917/127801168-d2a610c6-faa3-4246-ba8c-42c663030ccb.png">

**Comment by fasttime** [comment]
You want to enter a string literal inside a string literal in JavaScript. The syntax for that requires nested quotation marks and double-escaped backslashes:

```js
let res_0 = JScrewIt.encode('"\\\\"');
let res_1 = JScrewIt.encode('"\\""');
```

If that looks too quirky (and it is... I can't change it...) you can use [`JSON.stringify`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) to apply nested quotation and double escaping to your input string as needed.

```js
let res_0 = JScrewIt.encode(JSON.stringify('\\'));
let res_1 = JScrewIt.encode(JSON.stringify('"'));
```

Hope this helps.

**Comment by xfeng96** [comment]
@fasttime Thanks a lot. It works!
