### ISSUE TITLE
Bug when converting some strings begin with "Infinity"

### ISSUE THREAD

**Issue by Clayblockunova** [fasttime/JScrewIt#42]
when I tried to convert "Infinitywhitenight" in Edge, a 1201-chars-code is returned and evals into "infinit". why would this happen? will this be fixed?

**Comment by fasttime** [comment]
There is a bug in an optimizer which is incorrectly assuming that a solutions source is always a single character, but the source could also be a string like `"Infinity"`, `"true"`, `"undefined"`, etc.

https://github.com/fasttime/JScrewIt/blob/a58bc6180bc58bf8c9db2235ea2aaf176d007207/src/lib/optimizers/to-string-optimizer.js#L193-L198

I will fix this as soon as I have a chance.

**Comment by fasttime** [comment]
Fixed in [2.35.1](/fasttime/JScrewIt/releases/tag/2.35.1). Thanks for reporting this!
